import type { Policy, Tool, TeamMember } from './types';
import { ToolActionType } from './types';
import { PdfGearIcon } from './components/icons/PdfGearIcon';
import { VSCodeIcon } from './components/icons/VSCodeIcon';
import { GitIcon } from './components/icons/GitIcon';
import { NotepadPlusPlusIcon } from './components/icons/NotepadPlusPlusIcon';
import { AutodeskIcon } from './components/icons/AutodeskIcon';
import { ZohoIcon } from './components/icons/ZohoIcon';
import { TeamsIcon } from './components/icons/TeamsIcon';
import { HexagonIcon } from './components/icons/HexagonIcon';
import { BentleyIcon } from './components/icons/BentleyIcon';
import { AspenTechIcon } from './components/icons/AspenTechIcon';
import { AutoCADIcon } from './components/icons/AutoCADIcon';
import { AvevaIcon } from './components/icons/AvevaIcon';
import { OracleIcon } from './components/icons/OracleIcon';
import { MsOfficeIcon } from './components/icons/MsOfficeIcon';
import { SolidWorksIcon } from './components/icons/SolidWorksIcon';


export const ONBOARDING_STEPS: string[] = [
  'Review Company Policies',
  'Your Information',
  'ID Card',
  'Provident Fund',
  'Worksheet',
];

export const POLICIES: Policy[] = [
  // In a real-world application, the 'url' for each policy would point to a PDF file
  // hosted on a secure company server or a Content Delivery Network (CDN).
  { id: 1, title: 'Code of Conduct', description: 'Outlines the standards of behavior expected from all employees, promoting a positive and respectful workplace.', url: '/policies/Code_of_Conduct.pdf', version: 'v4.1' },
  { id: 2, title: 'Core Values', description: 'Defines the fundamental beliefs and principles that guide our company culture and business practices.', url: '/policies/Core_Values.pdf', version: 'v2.0' },
  { id: 3, title: 'DDS Quality Policy', description: 'Details our commitment to quality in all services and the processes we follow to ensure customer satisfaction.', url: '/policies/DDS_Quality_Policy.pdf', version: 'v1.5' },
  { id: 4, title: 'DDS Risk Assessment Policy', description: 'Establishes the framework for identifying, analyzing, and mitigating risks across the organization.', url: '/policies/DDS_Risk_Assessment_Policy.pdf', version: 'v1.2' },
  { id: 5, title: 'Energy Conservation Policy', description: 'Guidelines and initiatives for reducing energy consumption and promoting sustainability in the workplace.', url: '/policies/Energy_Conservation_Policy.pdf', version: 'v1.8' },
  { id: 6, title: 'Information and Data Security Policy', description: 'Mandatory guidelines for protecting company, client, and employee data from unauthorized access.', url: '/policies/Information_Data_Security.pdf', version: 'v3.2' },
  { id: 7, title: 'Leave Policy for Women Employees', description: 'Specific provisions and entitlements regarding maternity and other forms of leave for women employees.', url: '/policies/Leave_Policy_Women.pdf', version: 'v2.6' },
  { id: 8, title: 'Mission', description: 'A formal summary of the aims and values of our company.', url: '/policies/Mission.pdf', version: 'v1.0' },
  { id: 9, title: 'Network Security Policy', description: 'Rules and procedures for the use and security of the company\'s network infrastructure.', url: '/policies/Network_Security_Policy.pdf', version: 'v2.3' },
  { id: 10, title: 'Physical Security Policy', description: 'Measures to protect personnel, hardware, and physical locations from harm or unauthorized access.', url: '/policies/Physical_Security_Policy.pdf', version: 'v2.1' },
  { id: 11, title: 'Sexual Harassment Policy', description: 'A zero-tolerance policy outlining prevention, reporting procedures, and consequences for sexual harassment.', url: '/policies/Sexual_Harassment_Policy.pdf', version: 'v3.0' },
  { id: 12, title: 'Vision', description: 'Describes the desired future position of the company.', url: '/policies/Vision.pdf', version: 'v1.0' },
  { id: 13, title: 'Waste Management Policy', description: 'Procedures for the responsible management and disposal of waste to minimize environmental impact.', url: '/policies/Waste_Management_Policy.pdf', version: 'v1.4' },
];


export const TEAM_MEMBERS: TeamMember[] = [
    {
        id: '1',
        name: 'Alice Johnson',
        employeeId: 'EMP001',
        role: 'Lead Engineer',
        department: 'Engineering',
        email: 'alice.j@onbordeasy.com',
        imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG9otby1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=60',
    },
    {
        id: '2',
        name: 'Bob Williams',
        employeeId: 'EMP002',
        role: 'Product Manager',
        department: 'Product',
        email: 'bob.w@onbordeasy.com',
        imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG9otby1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=60',
    },
    {
        id: '3',
        name: 'Charlie Brown',
        employeeId: 'EMP003',
        role: 'UI/UX Designer',
        department: 'Design',
        email: 'charlie.b@onbordeasy.com',
        imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG9otby1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=60',
    },
    {
        id: '4',
        name: 'Diana Prince',
        employeeId: 'EMP004',
        role: 'Frontend Developer',
        department: 'Engineering',
        email: 'diana.p@onbordeasy.com',
        imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG9otby1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=60',
    },
    {
        id: '5',
        name: 'Ethan Hunt',
        employeeId: 'EMP005',
        role: 'Backend Developer',
        department: 'Engineering',
        email: 'ethan.h@onbordeasy.com',
        imageUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG9otby1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=60',
    },
    {
        id: '6',
        name: 'Fiona Glenanne',
        employeeId: 'EMP006',
        role: 'QA Engineer',
        department: 'Engineering',
        email: 'fiona.g@onbordeasy.com',
        imageUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG9otby1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=60',
    },
];

export const TOOLS: Tool[] = [
  {
    id: 'smart3d',
    name: 'Smart 3D',
    logo: HexagonIcon,
    description: 'A data-centric, rule-driven solution for streamlining engineering design processes in plant design.',
    category: '3D Modelling & Plant Design',
    version: '2024',
    lastUpdated: '2024-05-01',
    actionType: ToolActionType.REQUEST_IT,
    downloadUrl: `https://hexagon.com/products/smart-3d`,
  },
  {
    id: 'aveva-e3d',
    name: 'AVEVA E3D Design',
    logo: AvevaIcon,
    description: 'Advanced 3D design software for the process plant, marine, and power industries.',
    category: '3D Modelling & Plant Design',
    version: '3.3',
    lastUpdated: '2024-04-20',
    actionType: ToolActionType.REQUEST_IT,
    downloadUrl: `https://www.aveva.com/en/products/e3d-design/`,
  },
  {
    id: 'cadworx',
    name: 'CADWorx Plant Professional',
    logo: HexagonIcon,
    description: 'Intelligent 3D plant design and modeling software for AutoCAD and BricsCAD platforms.',
    category: '3D Modelling & Plant Design',
    version: '2024',
    lastUpdated: '2024-03-15',
    actionType: ToolActionType.REQUEST_IT,
    downloadUrl: `https://hexagon.com/products/cadworx-plant-design-suite`,
  },
  {
    id: 'solidworks',
    name: 'SolidWorks',
    logo: SolidWorksIcon,
    description: '3D CAD design software for creating, simulating, publishing, and managing your data.',
    category: '3D Modelling & Plant Design',
    version: '2024 SP2',
    lastUpdated: '2024-05-02',
    actionType: ToolActionType.REQUEST_IT,
    downloadUrl: `https://www.solidworks.com/`,
  },
  {
    id: 'autocad',
    name: 'AutoCAD',
    logo: AutoCADIcon,
    description: 'Industry-standard software for 2D and 3D computer-aided design and drafting.',
    category: '2D Drafting',
    version: '2025',
    lastUpdated: '2024-03-28',
    actionType: ToolActionType.REQUEST_IT,
    downloadUrl: `https://www.autodesk.com/products/autocad/overview`,
  },
  {
    id: 'microstation',
    name: 'Bentley MicroStation',
    logo: BentleyIcon,
    description: 'Powerful 2D/3D CAD software for architecture, engineering, construction, and operations.',
    category: '2D Drafting',
    version: '10.17',
    lastUpdated: '2024-05-10',
    actionType: ToolActionType.REQUEST_IT,
    downloadUrl: `https://www.bentley.com/software/microstation/`,
  },
  {
    id: 'smartsketch',
    name: 'SmartSketch',
    logo: HexagonIcon,
    description: 'A versatile and cost-effective precision engineering and drafting product for various design disciplines.',
    category: '2D Drafting',
    version: '2023',
    lastUpdated: '2024-03-20',
    actionType: ToolActionType.REQUEST_IT,
    downloadUrl: `https://hexagon.com/products/smartsketch`,
  },
  {
    id: 'aspen-hysys',
    name: 'Aspen HYSYS',
    logo: AspenTechIcon,
    description: 'Comprehensive process simulation software used to mathematically model chemical processes.',
    category: 'Process Simulation',
    version: 'V14',
    lastUpdated: '2024-02-10',
    actionType: ToolActionType.REQUEST_IT,
    downloadUrl: `https://www.aspentech.com/en/products/engineering/aspen-hysys`,
  },
  {
    id: 'caesar2',
    name: 'CAESAR II',
    logo: HexagonIcon,
    description: 'The industry standard for pipe stress analysis, allowing for static and dynamic analysis of piping systems.',
    category: 'Stress & Structural Analysis',
    version: 'v13.0',
    lastUpdated: '2024-04-15',
    actionType: ToolActionType.REQUEST_IT,
    downloadUrl: `https://hexagon.com/products/caesar-ii`,
  },
  {
    id: 'staad-pro',
    name: 'STAAD.Pro',
    logo: BentleyIcon,
    description: '3D structural analysis and design software for any type of structure, such as buildings, bridges, and towers.',
    category: 'Stress & Structural Analysis',
    version: 'CONNECT V22',
    lastUpdated: '2024-01-25',
    actionType: ToolActionType.REQUEST_IT,
    downloadUrl: `https://www.bentley.com/software/staad-pro/`,
  },
  {
    id: 'navisworks',
    name: 'Navisworks Freedom',
    logo: AutodeskIcon,
    description: 'Free viewer for NWD and DWF file formats. Enables viewing of 3D models and simulations.',
    category: 'Review Software',
    version: '2025',
    lastUpdated: '2024-04-05',
    actionType: ToolActionType.DIRECT_DOWNLOAD,
    downloadUrl: `https://www.autodesk.com/products/navisworks/navisworks-freedom`,
  },
  {
    id: 'primavera-p6',
    name: 'Primavera P6',
    logo: OracleIcon,
    description: 'High-performance project management software for planning, managing, and executing projects.',
    category: 'Project Management',
    version: '23.12',
    lastUpdated: '2023-12-15',
    actionType: ToolActionType.REQUEST_IT,
    downloadUrl: `https://www.oracle.com/industries/construction-engineering/primavera-p6/`,
  },
  {
    id: 'msproject',
    name: 'Microsoft Project',
    logo: MsOfficeIcon,
    description: 'Project management software to help you execute projects with ease. Part of the Microsoft 365 family.',
    category: 'Project Management',
    version: 'Plan 3',
    lastUpdated: '2024-05-20',
    actionType: ToolActionType.REQUEST_IT,
    downloadUrl: `https://www.microsoft.com/en-us/microsoft-365/project/project-management-software`,
  },
  {
    id: 'msoffice',
    name: 'Microsoft 365 Suite',
    logo: MsOfficeIcon,
    description: 'Essential productivity apps including Word, Excel, PowerPoint, and Outlook.',
    category: 'Communication & Utility',
    version: '2405',
    lastUpdated: '2024-05-21',
    actionType: ToolActionType.REQUEST_IT,
    downloadUrl: 'https://www.microsoft.com/en-us/microsoft-365',
  },
  {
    id: 'msteams',
    name: 'Microsoft Teams',
    logo: TeamsIcon,
    description: 'The ultimate messaging app for your organization—a workspace for real-time collaboration.',
    category: 'Communication & Utility',
    version: '2.1',
    lastUpdated: '2024-05-21',
    actionType: ToolActionType.DIRECT_DOWNLOAD,
    downloadUrl: `https://www.microsoft.com/en-us/microsoft-teams/download-app`,
  },
  {
    id: 'zohomail',
    name: 'Zoho Mail Desktop',
    logo: ZohoIcon,
    description: 'Desktop client for Zoho Mail to access your inbox, calendar, and contacts from your computer.',
    category: 'Communication & Utility',
    version: '1.5.4',
    lastUpdated: '2024-04-22',
    actionType: ToolActionType.DIRECT_DOWNLOAD,
    downloadUrl: `https://www.zoho.com/mail/desktop/`,
  },
  {
    id: 'zohocliq',
    name: 'Zoho Cliq',
    logo: ZohoIcon,
    description: 'Team communication and collaboration software with chat, channels, and video calls.',
    category: 'Communication & Utility',
    version: '4.1',
    lastUpdated: '2024-05-18',
    actionType: ToolActionType.DIRECT_DOWNLOAD,
    downloadUrl: `https://www.zoho.com/cliq/apps.html`,
  },
  {
    id: 'pdfgear',
    name: 'PDFgear',
    logo: PdfGearIcon,
    description: 'A complete freeware PDF editor and reader with comprehensive features.',
    category: 'Communication & Utility',
    version: '2.1.0',
    lastUpdated: '2024-05-10',
    actionType: ToolActionType.DIRECT_DOWNLOAD,
    downloadUrl: `https://www.pdfgear.com/`,
  },
  {
    id: 'notepadplusplus',
    name: 'Notepad++',
    logo: NotepadPlusPlusIcon,
    description: 'A free source code editor and Notepad replacement that supports several languages.',
    category: 'Communication & Utility',
    version: '8.6.7',
    lastUpdated: '2024-05-01',
    actionType: ToolActionType.DIRECT_DOWNLOAD,
    downloadUrl: `https://notepad-plus-plus.org/downloads/`,
  },
  {
    id: 'vscode',
    name: 'Visual Studio Code',
    logo: VSCodeIcon,
    description: 'Popular code editor for developers with extensive extension support.',
    category: 'Developer Tools',
    version: '1.89.1',
    lastUpdated: '2024-05-08',
    actionType: ToolActionType.DIRECT_DOWNLOAD,
    downloadUrl: `https://code.visualstudio.com/download`,
  },
    {
    id: 'git',
    name: 'Git',
    logo: GitIcon,
    description: 'Version control system to track changes in source code during development.',
    category: 'Developer Tools',
    version: '2.45.0',
    lastUpdated: '2024-05-13',
    actionType: ToolActionType.DIRECT_DOWNLOAD,
    downloadUrl: `https://git-scm.com/downloads`,
  },
];